### ISSUE TITLE
How do we log the quote?

### ISSUE THREAD

**Issue by MGTHEBOSS** [RadarTech/redshift-monorepo#86]
Hi,

We would like to log the quote received from the `requestQuote` method. Using `then` is not logging anything. We appreciate your cooperation.

**Comment by cavanmflynn** [comment]
If no quote is returned in the `then` method, then you have an error in your request. Likely an invalid or unpayable invoice.

Use the `catch` method to view the error:

```typescript
redshift.ws
  .requestQuote(request)
  .then(quote => console.log('QUOTE:', quote))
  .catch(error => console.log('ERROR:', error.message));
```

**Comment by MGTHEBOSS** [comment]
@cavanmflynn Please see the code here, https://glitch.com/edit/#!/join/63d52f43-f9c5-44a1-87a3-ca9b0ba6ce22 .

**Comment by MGTHEBOSS** [comment]
The issue is resolved.

**Comment by MGTHEBOSS** [comment]
It's sometimes logging `ERROR: InvoiceAmountBelowMinimum` and sometimes nothing. The error goes away when we use a new invoice from bottle.li and reappears after running the code a few times. Please explain the error. The issue of nothing getting logged is not going away. Please resolve the issue. We appreciate your cooperation.

**Comment by cavanmflynn** [comment]
Looking at the code, you shouldn't be using async/await and then/catch at the same time. Use one or the other.

```typescript
try {
  const client = new redshiftJs.WebSocketClient();

  await client.connect();

  const quote = await client.requestQuote({
      market: redshiftJs.Market.BTC_LBTC, // bitcoin <-> lightning bitcoin
      invoice: 'lnbc10n1pwu6lhkpp5n6vljvjkz6zmavh5yw2jv8dhxdgh0yvkwe058wgujrmvy760vctsdqqcqzpgh0uvcstq6v6k9td8evgm9w0g5vqs4cmu2jkrr3ag74eq204yh6nhp2s0nae9kdjv6xl3q8n3kqnspclpmtcn56qy8fsmu9adea830hgqttfe6t',
      refundAddress: '1EVQK91h6WiUesAbpQXu9Ryvip6vdqgsUj',
  });
  console.log('QUOTE:', quote);
} catch (error) {
  console.log('ERROR:', error);
}
```

**Comment by cavanmflynn** [comment]
`ERROR: InvoiceAmountBelowMinimum` means that the amount of the invoice you're attempting to request a quote for is below the minimum amount required by Redshift.

**Comment by MGTHEBOSS** [comment]
@cavanmflynn We have made the changes advised. The issue persists. What is the minimum amount required by redshift?

**Comment by MGTHEBOSS** [comment]
We created an invoice to receive 4M sat and now we are getting `InvoiceAmountAboveMaximum` error. Please also tell us the maximum amount allowed.

**Comment by MGTHEBOSS** [comment]
We were able to get a quote after using an invoice to receive 1 M sat.

**Comment by cavanmflynn** [comment]
@MGTHEBOSS Good to hear! For bitcoin, the minimum is 30,000 sats and the maximum is 1,000,000. Amount requirements for markets can be found [here](https://api.redshift.radar.tech/api/markets/requirements).
